### ISSUE TITLE
部分功能不会使用

### ISSUE THREAD

**Issue by uhFan** [742481030/oneindex#6]
首先非常感谢作者写出这么好用的工具，但是在使用过程中，我对某些功能的使用方法不太了解。
超级缓存，代理设置点进去就会404。请问该怎么设置才能正常使用。

**Comment by Palpitace** [comment]
臣复议

**Comment by 742481030** [comment]
> 首先非常感谢作者写出这么好用的工具，但是在使用过程中，我对某些功能的使用方法不太了解。
> 超级缓存，代理设置点进去就会404。请问该怎么设置才能正常使用。

 缓存功能管理员模式关闭了,会导致管理功能异常,代理设置在基本设置里填写域名,和反向代理即可,缓存功能和预先加载功能(加快游客访问速度)目前被本人写死,,也就是游客访问主页会自动缓存子页面,并且刷新会返回304状态码,直到token过期服务器才返回网页,否则使用缓存,以减少流量.消耗并且加快浏览速度,由于一只在添加新功能和新功能所出现的bug调试中恶性循环,

**Comment by 742481030** [comment]
由于 程序原作者用了大量静态方法,导致本人恶性循环中,也是不知所措.
Because the author of the program used a lot of static methods, I was at a loss in the vicious circle

**Comment by uhFan** [comment]
感谢回复，目前的功能已经能完全满足我的需求了，谢谢！
